#!/usr/bin/env bash
set -e
cmd=${1:-run}
echo $cmd

echo "starting etcd..."
docker stop etcd && docker rm etcd
docker run -d -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.4.9 \
    /usr/local/bin/etcd \
    --advertise-client-urls http://0.0.0.0:2379 \
    --listen-client-urls http://0.0.0.0:2379 \
    --initial-advertise-peer-urls http://0.0.0.0:2380 \
    --listen-peer-urls http://0.0.0.0:2380 \
    --initial-cluster "default=http://0.0.0.0:2380"

while ! nc -z localhost 2379; do   
  echo "waiting for etcd..."
  sleep 0.1 
done

case $cmd in
  "test" )
     RUSTFLAGS="$RUSTFLAGS -A dead_code" cargo test --all
     echo "stopping etcd..."
     docker exec etcd etcdctl del ledgers --prefix
     docker stop etcd && docker rm etcd
     ;;
  * )
     docker exec etcd etcdctl put ledgers.local 127.0.0.1:7878
     cargo run -- --port 7878 
esac
