#!/usr/bin/env bash
set -e

echo "starting etcd..."
docker stop etcd && docker rm etcd

docker run -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.4.9 \
    /usr/local/bin/etcd \
    --advertise-client-urls http://0.0.0.0:2379 \
    --listen-client-urls http://0.0.0.0:2379 \
    --initial-advertise-peer-urls http://0.0.0.0:2380 \
    --listen-peer-urls http://0.0.0.0:2380 \
    --initial-cluster "default=http://0.0.0.0:2380"

while ! nc -z localhost 2379; do   
  echo "waiting for etcd..."
  sleep 0.1 
done

RUSTFLAGS="$RUSTFLAGS -A dead_code" cargo test

echo "stopping etcd..."
docker stop etcd && docker rm etcd

